- name: Fuse Standalone Playbook
  hosts: fuse-lab-environment
  serial: 1
  remote_user: root
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
        # Two Fuse Standalone with a Network of Brokers
        - { role: fuse-standalone, esb_name: 'esb01',  port_offset: '0', nob: 'true' }
        - { role: fuse-standalone, esb_name: 'esb02',  port_offset: '100', nob: 'true' }
        # Two Fuse Standalone without a Network of Brokers
        # - { role: fuse-standalone, esb_name: 'esb01',  port_offset: '0', nob: 'false' }
        # - { role: fuse-standalone, esb_name: 'esb02',  port_offset: '100', nob: 'false' }
        # One Fuse Standalone with Full profiles and One Fuse Standalone without A-MQ profile
        # - { role: fuse-standalone, esb_name: 'esb01',  port_offset: '0', nob: 'true' }
        # - { role: fuse-standalone, esb_name: 'esb02',  port_offset: '100', esb_type: 'noamq' }
